=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidras.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/sidras" elementFormDefault="qualified" targetNamespace="http://tempuri.org/sidras" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sidras">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="sidra" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sidra">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo" />
        <xs:element ref="rutaFoto" />
        <xs:element ref="nombre" />
        <xs:element ref="descripcion" />
        <xs:element ref="precio" />
        <xs:element ref="porcentaje_alcohol" />
        <xs:element ref="cantidad_neta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string" />
  <xs:element name="rutaFoto" type="xs:string" />
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="precio">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="porcentaje_alcohol">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:double">
          <xs:attribute name="cantidad" type="xs:string" use="required" />
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="cantidad_neta">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="cantidad" type="xs:string" use="required" />
          <xs:attribute name="unidad" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidrasEspumosas.xml
<?xml version="1.0" encoding="UTF-8"?>
<sidras xmlns="http://tempuri.org/sidras"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://tempuri.org/sidras sidras.xsd">

     <sidra>
         <titulo>EL GAITERO sidra achampanada etiqueta blanca botella 75 cl.</titulo>
         <rutaFoto>../img/00118730600188____2__600x600.jpg</rutaFoto>
         <nombre>El Gaitero</nombre>
         <descripcion>La sidra tradicional de El Gaitero por excelencia, espumosa, que empezó a producirse ya a finales del siglo XIX en todo el mundo. Ésta es una sidra semiseca singular, obtenida por elaboración tradicional y de gran riqueza aromática, espumosa y con formación de rosarios de gran finura en la burbuja.</descripcion>
         <precio unidad="€">1,52</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">4.1</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>SIDRA BRUT POMARINA D.O.P.</titulo>
         <rutaFoto>../img/sidra-el-gaitero-etiqueta-negra.jpg</rutaFoto>
         <nombre>Pomarina Brut</nombre>
         <descripcion>Color Amarillo dorado limpio y brillante con burbuja fina. La sidra Pomarina Brut proviene de plantaciones nuevas de fincas con Denominación de Origen Protegida. Su elaboración se caracteriza por realizar la ultima fase de la fermentación de manera presurizada para integrar mejor la burbuja. Esta sidra es una espumosa en su variedad Brut, con sabor fresco y elegante</descripcion>
         <precio unidad="€">6,35</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">4</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>Sidra Lagar de Camin Brut</titulo>
         <rutaFoto>../img/papa.jpg</rutaFoto>
         <nombre>Pomarina Brut</nombre>
         <descripcion>La sidra lagar de Camin Brut es una sidra espumosa totalmente natural. También se conoce como sidra achampanada o brut de manzana. Ideal para celebraciones!</descripcion>
         <precio unidad="€">3,43</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">4.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>SIDRA POMAR ROSEE VIUDA ANGELON</titulo>
         <rutaFoto>../img/papa.jpg</rutaFoto>
         <nombre>Pomar Rosee</nombre>
         <descripcion>Sidra espumosa elaborada a partir de las propias manzanas que Viuda de Angelón tiene en la localidad de Monga (Nava, Asturias).</descripcion>
         <precio unidad="€">3,75</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>
 </sidras>
