=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidras.dtd
<!ELEMENT sidras (sidra)*>
        <!ELEMENT sidra (titulo, rutaFoto, nombre, descripcion, composicion, precio, porcentaje_alcohol, cantidad_neta )>
        <!ELEMENT titulo (#PCDATA)>
	<!ELEMENT rutaFoto (#PCDATA)>
	<!ELEMENT nombre (#PCDATA)>    
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT composicion (compuesto+)>
        <!ELEMENT compuesto (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
	<!ATTLIST precio
                unidad CDATA #REQUIRED>
        <!ELEMENT porcentaje_alcohol (#PCDATA)>
        <!ATTLIST porcentaje_alcohol
                cantidad CDATA #REQUIRED
                unidad CDATA #REQUIRED>
	<!ELEMENT cantidad_neta (#PCDATA)>
        <!ATTLIST cantidad_neta
                unidad CDATA #REQUIRED>

=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sidras SYSTEM "sidras.dtd">
 <sidras>
     <sidra>
         <titulo>Sidra Menéndez natural 70 cl.</titulo>
         <rutaFoto>../IMG/00118731500114____1__600x600.jpg</rutaFoto>
         <nombre>Menéndez</nombre>
         <descripcion>Tonos dorados. Buena intensidad con aromas florales a manzana. Sabor fresco y ligera acidez con una larga persistencia en boca.</descripcion>
         <precio unidad="€">1,85</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>
     
     <sidra>
         <titulo>MANUEL BUSTO sidra natural botella 70 cl.</titulo>
         <rutaFoto>../IMG/mbustosidra2.jpg</rutaFoto>
         <nombre>M.Busto</nombre>
         <descripcion>Sidra Natural  ”tradicional” o “en rama”, elaborada a partir de manzanas asturianas seleccionadas de variedades dulces, amargas y ácidas con posterior fermentación en toneles de castaño.</descripcion>
         <precio unidad="€">2,75</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>Botella sidra Trabanco natural 75 cl.</titulo>
         <rutaFoto>../IMG/botella-sidra-trabanco.jpg</rutaFoto>
         <nombre>Trabanco</nombre>
         <descripcion>Trabanco elabora su sidra desde el año 1925 siguiendo una gran tradición sidrera. Es conocida desde siempre por su buen saber hacer y su gran calidad. Es elaborada con las mejores variedades de manzana de sidra a partir de un mosto de manzana 100% natural, que fermentará con levaduras naturales bajo temperaturas controladas en toneles de castaño.</descripcion>
         <precio unidad="€">2,10</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

      <sidra>
         <titulo>VILLACUBERA SIDRA DE ASTURIAS D.O.P.</titulo>
         <rutaFoto>../IMG/villacubera-sidra-de-asturias-dop.jpg</rutaFoto>
         <nombre>Villacubera</nombre>
         <descripcion>Villacubera es una sidra natural única, sidra con Denominación de Origen Asturias. Se elabora con exclusivas manzanas de las mejores pomaradas de la región asturiana. Una sidra agresiva que solo se suaviza con una larga maduración en bodega. Su aroma es fino, rico en matices, y al es paladar suave y sabroso, con sutiles notas amargas</descripcion>
         <precio unidad="€">2,60</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>BOTELLA SIDRA ASTURIANA CABAÑON</titulo>
         <rutaFoto>../IMG/botella-sidra-asturiana-cabanon.jpg</rutaFoto>
         <nombre>Cabañón</nombre>
         <descripcion>La Sidra Cabañon se elabora en Naves de Llanes, y está considerada una de las mejores sidras del oriente asturiano, es una sidra casera. Servir fría</descripcion>
         <precio unidad="€">2,90</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>BOTELLA SIDRA ASTURIANA CABAÑON</titulo>
         <rutaFoto>../IMG/botella-sidra-asturiana-cabanon.jpg</rutaFoto>
         <nombre>Cabañón</nombre>
         <descripcion>La Sidra Cabañon se elabora en Naves de Llanes, y está considerada una de las mejores sidras del oriente asturiano, es una sidra casera. Servir fría</descripcion>
         <precio unidad="€">2,90</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>Sidra Fanjul Natural</titulo>
         <rutaFoto>../IMG/resize_image.jpg</rutaFoto>
         <nombre>Fanjul</nombre>
         <descripcion>La Sidra Fanjul Natural es seca, ligeramente  ácida y fina astringencia final, destacando su frescor y aroma de manzana. Con color amarillo pálido y finos reflejos verdes</descripcion>
         <precio unidad="€">2,32</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">5.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>

     <sidra>
         <titulo>Sidra Fanjul Natural</titulo>
         <rutaFoto>../IMG/resize_image.jpg</rutaFoto>
         <nombre>Fanjul</nombre>
         <descripcion>La Sidra Fanjul Natural es seca, ligeramente  ácida y fina astringencia final, destacando su frescor y aroma de manzana. Con color amarillo pálido y finos reflejos verdes</descripcion>
         <precio unidad="€">2,32</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">5.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>
 </sidras>
