=== giramos/App-for-online-sale/El_Llagar_Online/XML/Sidra.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT sidras (sidra)*>
        <!ELEMENT sidra (titulo, rutaFoto, nombre, descripcion, precio, porcentaje_alcohol, cantidad_neta )>
        <!ELEMENT titulo (#PCDATA)>
		<!ELEMENT rutaFoto (#PCDATA)>
		<!ELEMENT nombre (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
		<!ATTLIST precio
                unidad CDATA #REQUIRED>
        <!ELEMENT porcentaje_alcohol (#PCDATA)>
        <!ATTLIST porcentaje_alcohol
                cantidad CDATA #REQUIRED
                unidad CDATA #REQUIRED>
		<!ELEMENT cantidad_neta (#PCDATA)>
        <!ATTLIST cantidad_neta
                cantidad CDATA #REQUIRED
                unidad CDATA #REQUIRED>

=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sidras SYSTEM "Sidra.dtd">
 <sidras>
     <sidra>
         <titulo>Sidra Menéndez natural 70 cl.</titulo>
         <rutaFoto>../img/00118731500114____1__600x600.jpg</rutaFoto>
         <nombre>Menéndez</nombre>
         <descripcion>Tonos dorados. Buena intensidad con aromas florales a manzana. Sabor fresco y ligera acidez con una larga persistencia en boca.</descripcion>
         <precio unidad="€">1,85</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>
     
     <sidra>
         <titulo>MANUEL BUSTO sidra natural botella 70 cl</titulo>
         <rutaFoto>../img/mbustosidra2.jpg</rutaFoto>
         <nombre>M.Busto</nombre>
         <descripcion>Sidra Natural  ”tradicional” o “en rama”, elaborada a partir de manzanas asturianas seleccionadas de variedades dulces, amargas y ácidas con posterior fermentación en toneles de castaño.</descripcion>
         <precio unidad="€">2,75</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">6.5</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">70</cantidad_neta>
     </sidra>
 </sidras>

=== giramos/App-for-online-sale/El_Llagar_Online/XML/sidraEspumosa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sidras SYSTEM "Sidra.dtd">
 <sidras>
     <sidra>
         <titulo>EL GAITERO sidra achampanada etiqueta blanca botella 75 cl.</titulo>
         <rutaFoto>../img/00118730600188____2__600x600.jpg</rutaFoto>
         <nombre>El Gaitero</nombre>
         <descripcion>La sidra tradicional de El Gaitero por excelencia, espumosa, que empezó a producirse ya a finales del siglo XIX en todo el mundo. Ésta es una sidra semiseca singular, obtenida por elaboración tradicional y de gran riqueza aromática, espumosa y con formación de rosarios de gran finura en la burbuja.</descripcion>
         <precio unidad="€">1,52</precio>
         <porcentaje_alcohol cantidad="100" unidad="%">4.1</porcentaje_alcohol>
         <cantidad_neta cantidad="100" unidad="cl">75</cantidad_neta>
     </sidra>
 </sidras>
